'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  async up(queryInterface, _Sequelize) {
    const cities = [
      {
        city_name: 'Cần Thơ',
        city_code: 'Cần Thơ_Cần Thơ',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Đà Nẵng',
        city_code: 'Đà Nẵng_Đà Nẵng',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Hải Phòng',
        city_code: 'Hải Phòng_Hải Phòng',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Hà Nội',
        city_code: 'Hà Nội_Hà Nội',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Hồ Chí Minh',
        city_code: 'Hồ Chí Minh_Hồ Chí Minh',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Bà Rịa',
        city_code: 'Bà Rịa–Vũng Tàu_Bà Rịa',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Bạc Liêu',
        city_code: 'Bạc Liêu_Bạc Liêu',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Bắc Giang',
        city_code: 'Bắc Giang_Bắc Giang',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Bắc Ninh',
        city_code: 'Bắc Ninh_Bắc Ninh',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Bảo Lộc',
        city_code: 'Lâm Đồng_Bảo Lộc',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Biên Hòa',
        city_code: 'Đồng Nai_Biên Hòa',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Bến Tre',
        city_code: 'Bến Tre_Bến Tre',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Buôn Ma Thuột',
        city_code: 'Đắk Lắk_Buôn Ma Thuột',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Cà Mau',
        city_code: 'Cà Mau_Cà Mau',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Cẩm Phả',
        city_code: 'Quảng Ninh_Cẩm Phả',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Cao Lãnh',
        city_code: 'Đồng Tháp_Cao Lãnh',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Châu Đốc',
        city_code: 'An Giang_Châu Đốc',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Đà Lạt',
        city_code: 'Lâm Đồng_Đà Lạt',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Điện Biên Phủ',
        city_code: 'Điện Biên_Điện Biên Phủ',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Đông Hà',
        city_code: 'Quảng Trị_Đông Hà',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Đồng Hới',
        city_code: 'Quảng Bình_Đồng Hới',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Hà Tĩnh',
        city_code: 'Hà Tĩnh_Hà Tĩnh',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Hạ Long',
        city_code: 'Quảng Ninh_Hạ Long',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Hải Dương',
        city_code: 'Hải Dương_Hải Dương',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Hòa Bình',
        city_code: 'Hòa Bình_Hòa Bình',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Hội An',
        city_code: 'Quảng Nam_Hội An',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Huế',
        city_code: 'Thừa Thiên–Huế_Huế',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Hưng Yên',
        city_code: 'Hưng Yên_Hưng Yên',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Kon Tum',
        city_code: 'Kon Tum_Kon Tum',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Lạng Sơn',
        city_code: 'Lạng Sơn_Lạng Sơn',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Lào Cai',
        city_code: 'Lào Cai_Lào Cai',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Long Xuyên',
        city_code: 'An Giang_Long Xuyên',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Móng Cái',
        city_code: 'Quảng Ninh_Móng Cái',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Mỹ Tho',
        city_code: 'Tiền Giang_Mỹ Tho',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Nam Định',
        city_code: 'Nam Định_Nam Định',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Ninh Bình',
        city_code: 'Ninh Bình_Ninh Bình',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Nha Trang',
        city_code: 'Khánh Hòa_Nha Trang',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Cam Ranh',
        city_code: 'Khánh Hòa_Cam Ranh',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Phan Rang–Tháp Chàm',
        city_code: 'Ninh Thuận_Phan Rang–Tháp Chàm',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Phan Thiết',
        city_code: 'Bình Thuận_Phan Thiết',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Phủ Lý',
        city_code: 'Hà Nam_Phủ Lý',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Pleiku',
        city_code: 'Gia Lai_Pleiku',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Quảng Ngãi',
        city_code: 'Quảng Ngãi_Quảng Ngãi',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Quy Nhơn',
        city_code: 'Bình Định_Quy Nhơn',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Rạch Giá',
        city_code: 'Kiên Giang_Rạch Giá',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Sa Đéc',
        city_code: 'Đồng Tháp_Sa Đéc',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Sóc Trăng',
        city_code: 'Sóc Trăng_Sóc Trăng',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Sơn La',
        city_code: 'Sơn La_Sơn La',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Tam Kỳ',
        city_code: 'Quảng Nam_Tam Kỳ',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Tân An',
        city_code: 'Long An_Tân An',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Thái Bình',
        city_code: 'Thái Bình_Thái Bình',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Thái Nguyên',
        city_code: 'Thái Nguyên_Thái Nguyên',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Thanh Hóa',
        city_code: 'Thanh Hóa_Thanh Hóa',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Trà Vinh',
        city_code: 'Trà Vinh_Trà Vinh',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Tuy Hòa',
        city_code: 'Phú Yên_Tuy Hòa',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Tuyên Quang',
        city_code: 'Tuyên Quang_Tuyên Quang',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Uông Bí',
        city_code: 'Quảng Ninh_Uông Bí',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Việt Trì',
        city_code: 'Phú Thọ_Việt Trì',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Vinh',
        city_code: 'Nghệ An_Vinh',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Vĩnh Yên',
        city_code: 'Vĩnh Phúc_Vĩnh Yên',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Vĩnh Long',
        city_code: 'Vĩnh Long_Vĩnh Long',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Vũng Tàu',
        city_code: 'Bà Rịa–Vũng Tàu_Vũng Tàu',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Yên Bái',
        city_code: 'Yên Bái_Yên Bái',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        city_name: 'Cao Bằng',
        city_code: 'Cao Bằng_Cao Bằng',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];
    await queryInterface.bulkInsert('cities', cities, {});
  },

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  async down(queryInterface, _Sequelize) {
    await queryInterface.bulkDelete('cities', null, {});
  },
};
